// SPDX-License-Identifier: GPL-3.0
pragma solidity >=0.4.16 <0.9.0;
pragma experimental ABIEncoderV2;
import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@chainlink/contracts/src/v0.8/KeeperCompatible.sol";

contract RocketFactory is KeeperCompatibleInterface {
    Transaction[] transactionsList;
    //mapping for

    struct Transaction {
        uint256 id;
        address owner;
        address receiver;
        uint256 deadline;
        address ERC20TokenAddress;
        uint256 amount;
        uint256 tip;
        bool pending;
    }

    //creates a new transaction for later scheduling
    function createTransaction(
        address receiver,
        address ERC20TokenAddress,
        uint256 amount,
        uint256 deadline,
        uint256 tip
    ) public {
        // Check if they have the ERC20Token amount in their wallet
        uint256 dueBy = block.timestamp + deadline; //in seconds
        IERC20 token = IERC20(ERC20TokenAddress);
        require(
            token.allowance(msg.sender, address(this)) >= amount,
            "Not enough tokens to complete tx"
        );

        //Send that amount to the contract
        bool sent = token.transferFrom(msg.sender, address(this), amount);
        require(sent, "transfer fialed");

        Transaction memory newTransaction = Transaction(
            transactionsList.length,
            msg.sender,
            receiver,
            dueBy,
            ERC20TokenAddress,
            amount,
            tip,
            true
        );
        transactionsList.push(newTransaction);
    }

    //TODO
    // 1. send the money from the escrow account to the receiver
    // 2. (later) add a modifier that only allows approved liquidators to execute transaction
    //who can execute this transaction? only the liquidator bots
    function executeTransaction(uint256 id)
        public
        returns (Transaction memory)
    {
        //ensure that the transaction is not pending
        Transaction memory scheduledTx = getTransaction(id);
        require(scheduledTx.pending == true, "Already executed");
        // require( block.timestamp >= scheduledTx.deadline,"Not ready to be executed");

        //take the money from the lending pool and send it to the receiver
        //do this later

        // create a new struct and update the transactionsList
        Transaction memory newTransaction = Transaction(
            id,
            scheduledTx.owner,
            scheduledTx.receiver,
            scheduledTx.deadline,
            scheduledTx.ERC20TokenAddress,
            scheduledTx.amount,
            scheduledTx.tip,
            false
        );
        transactionsList[id] = newTransaction;
        return newTransaction;
    }

    //get the current transactions in the array
    function getAllTransactions() public view returns (Transaction[] memory) {
        return transactionsList;
    }

    function getTransaction(uint256 id)
        public
        view
        returns (Transaction memory)
    {
        require(id <= transactionsList.length);
        return transactionsList[id];
    }

    // Called by ChainLink Keeper every block to see if condition is met
    function checkUpkeep(
        bytes calldata /* checkData */
    )
        external
        view
        override
        returns (
            bool upkeepNeeded,
            bytes memory /* performData */
        )
    {
        // Get Array of all Pending Transactions
        Transaction[] memory allTxs = getAllTransactions();
        // Map thru all transaction to find where deadline < blocktime
        for (uint256 index = 0; index < allTxs.length; index++) {
            Transaction memory tx = allTxs[index];
            if (tx.deadline < block.timestamp) {
                upkeepNeeded == true;
            }
        }
    }

    function performUpkeep(
        bytes calldata /* performData */
    ) external override {
        // We highly recommend re-validating the upkeep in the performUpkeep function
        Transaction[] memory allTxs = getAllTransactions();
        // Map thru all transaction to find where deadline < blocktime
        for (uint256 index = 0; index < allTxs.length; index++) {
            Transaction memory tx = allTxs[index];
            if (tx.deadline < block.timestamp) {
                executeTransaction(tx.id);
            }
        }

        // We don't use the performData in this example. The performData is generated by the Keeper's call to your checkUpkeep function
    }
}
